id: 'skyvoid_worldgen_normal_end'
name: 'Normal End Sky Void'
author: 'BluePsychoRanger'
version: 1.0.1

require: 
  - src.plugins.worldgen.generate.base_with_end

data_pack:
  load: .

pipeline:
  - src.plugins.worldgen.get_empty_biomes.normal_end
